version: '3.8'

services:
  app:
    build: .
    container_name: clickdesign_app
    expose:
      - "80"
    environment:
      - CI_ENVIRONMENT=production
      - app.baseURL=https://clickdesign.com/
