import type { MarqueeThemePreset } from "./types";

export const PRESET_THEMES: MarqueeThemePreset = {
    id: 'reference-exact',
    name: 'Orijinal Görsel (1:1 Referans)',
    subtitle: 'Görseldeki siyah, mercan ve parlak kırmızı 3 katmanlı kesişen bant tasarımı',
    canvasBg: 'light-grid',
    bands: [
      {
        id: 'band-1',
        label: '1. Bant — Üst Çapraz Siyah Şerit',
        enabled: true,
        angle: '+8.5deg',
        verticalPos: '32%',
        colorScheme: 'charcoal',
        direction: 'left',
        speedSeconds: 48,
        zIndex: 10,
        initialOffsetClass: 'pl-[18vw]',
        hasShadow: false,
        items: [
          { id: 'b1-1', text: 'Animation', font: 'serif-slab' },
          { id: 'b1-2', text: 'User Experience', font: 'script-lobster' },
          { id: 'b1-3', text: 'AI', font: 'sans' },
          { id: 'b1-4', text: 'Motion Design', font: 'tech-wide' },
          { id: 'b1-5', text: '3D Visuals', font: 'slab-heavy' },
          { id: 'b1-6', text: 'Creative Direction', font: 'script-satisfy' },
        ],
      },
      {
        id: 'band-2',
        label: '2. Bant — Alt Çapraz Mercan Şerit',
        enabled: true,
        angle: '-14deg',
        verticalPos: '52%',
        colorScheme: 'coral',
        direction: 'right',
        speedSeconds: 48,
        zIndex: 20,
        initialOffsetClass: 'pl-[18vw]',
        hasShadow: false,
        items: [
          { id: 'b2-1', text: 'Frontend', font: 'sans' },
          { id: 'b2-2', text: 'Backend', font: 'script-kaushan' },
          { id: 'b2-3', text: 'Webflow', font: 'slab-heavy' },
          { id: 'b2-4', text: 'App Design', font: 'sans' },
          { id: 'b2-5', text: 'Design Systems', font: 'tech-wide' },
          { id: 'b2-6', text: 'Prototyping', font: 'script-satisfy' },
        ],
      },
      {
        id: 'band-3',
        label: '3. Bant — Ön Katman Kırmızı Şerit',
        enabled: true,
        angle: '+2.2deg',
        verticalPos: '46%',
        colorScheme: 'scarlet',
        direction: 'left',
        speedSeconds: 48,
        zIndex: 30,
        initialOffsetClass: 'pl-[19vw]',
        hasShadow: false,
        items: [
          { id: 'b3-1', text: 'Social Media', font: 'sans' },
          { id: 'b3-2', text: 'Logo', font: 'slab-heavy' },
          { id: 'b3-3', text: 'Branding', font: 'tech-wide' },
          { id: 'b3-4', text: 'Print', font: 'script-satisfy' },
          { id: 'b3-5', text: 'User Interface', font: 'sans' },
          { id: 'b3-6', text: 'Editorial', font: 'serif-slab' },
        ],
      },
    ],
  };
